@baseUrl= http://localhost:5110

// Get Books
GET {{baseUrl}}/books
Content-Type: application/json

{
  "PageNumber": 1,
  "PageSize": 10
}

###
@bookId = a89f6cd7-4693-457b-9009-02205dbbfe45
// Get Book by Id
GET {{baseUrl}}/book/{{bookId}}
Content-Type: application/json

###

// Create Book
POST {{baseUrl}}/book
Content-Type: application/json

{
  "Author":"Test_Author",
  "Title":"Test_Title",
  "Price":5.2
}

###

// Delete Book
DELETE {{baseUrl}}/book/0c6d98c0-91cb-461b-9b5f-12ba2e729df3
Content-Type: application/json

###

// Update Book
PUT {{baseUrl}}/book
Content-Type: application/json

{
      "id": "{{bookId}}",
      "title": "The Great Gatsby - Updated",
      "author": "F. Scott Fitzgerald - Updated",
      "price": 10.99,
      "rowVersion": "AAAAAAAAB9c="
}

###

// Update Book Price
PATCH {{baseUrl}}/book/{{bookId}}/pricehistory
Content-Type: application/json

{
  "newPrice": 5.27
}

###

// Create User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "userName":"Test_User",
  "email":"Test_User@gmail.com",
  "password":"User.123",
  "role":"Visitor"
}

###

