@baseUrl= https://localhost:7030

// Get Books
GET {{baseUrl}}/books
Content-Type: application/json

{
  "PageNumber": 1,
  "PageSize": 10
}

###
@bookId = a89f6cd7-4693-457b-9009-02205dbbfe45
// Get Book by Id
GET {{baseUrl}}/book/{{bookId}}
Content-Type: application/json

###

// Create Book
POST {{baseUrl}}/book
Content-Type: application/json

{
  "Author":"Test_Author",
  "Title":"Test_Title",
  "Price":5.2
}

###

// Delete Book
DELETE {{baseUrl}}/book/0c6d98c0-91cb-461b-9b5f-12ba2e729df3
Content-Type: application/json

###

// Update Book
PUT {{baseUrl}}/book
Content-Type: application/json

{
      "id": "{{bookId}}",
      "title": "The Great Gatsby - Updated",
      "author": "F. Scott Fitzgerald - Updated",
      "price": 10.99,
      "rowVersion": "AAAAAAAAB9c="
}

###

// Update Book Price
PATCH {{baseUrl}}/book/{{bookId}}/pricehistory
Content-Type: application/json

{
  "newPrice": 5.27
}

###

// Create User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "userName":"Test_User",
  "email":"Test_User@gmail.com",
  "password":"User.123",
  "role":"User"
}

###

// Login User
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email":"Test_User@gmail.com",
  "password":"User.123"
}

###

@token =eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdF9Vc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiVGVzdF9Vc2VyQGdtYWlsLmNvbSIsInJvbGUiOiJVc2VyIiwiZXhwIjoxNzMyODkwNzY5LCJpYXQiOjE3MzI4ODk4NjksIm5iZiI6MTczMjg4OTg2OX0.azoYUUn7h_1PFbqeqRJKDWXZQamGTfCbSX-GiLYDPzI

// Get List of CardItems
GET {{baseUrl}}/card
Accept: application/json
Authorization: Bearer {{token}}

###

// Add Book to the CardList
POST {{baseUrl}}/card
Accept: text/plain
Authorization: Bearer {{token}}
content-Type: application/json

{
  "bookId": "a89f6cd7-4693-457b-9009-02205dbbfe45",
  "quantity":3
}

###

