@baseUrl= http://localhost:5110

// Get Books
GET {{baseUrl}}/books
Content-Type: application/json

{
  "PageNumber": 1,
  "PageSize": 10
}

###

// Get Book by Id
GET {{baseUrl}}/book/1786b09f-570b-44a2-9bda-e58a838d7d7c
Content-Type: application/json

###

// Create Book
POST {{baseUrl}}/book
Content-Type: application/json

{
  "Author":"Test_Author",
  "Title":"Test_Title",
  "Price":5.2
}

###

// Delete Book
DELETE {{baseUrl}}/book/1786b09f-570b-44a2-9bda-e58a838d7d7c
Content-Type: application/json

###

// Update Book
PUT {{baseUrl}}/book
Content-Type: application/json

{
      "id": "11111111-1111-1111-1111-111111111111",
      "title": "The Great Gatsby - Updated",
      "author": "F. Scott Fitzgerald - Updated",
      "price": 10.99
}

###

// Update Book Price
PATCH {{baseUrl}}/book/11111111-1111-1111-1111-111111111111/pricehostory
Content-Type: application/json

{
  "newPrice": 5.2
}

